osx_image: xcode11
language: swift
script:
- xcrun simctl list runtimes
- xcrun instruments -s devices
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/BSCountryViewController.xcworkspace -scheme BSCountryViewController-Example -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)